solids:
  get_param_epoch:
    config:
      param_epoch: 0
  get_epoch_10:
    config:
      param_epoch: 9
  get_epoch_2:
    config:
      param_epoch: 1
  get_epoch_3:
    config:
      param_epoch: 2
  get_epoch_4:
    config:
      param_epoch: 3
  get_epoch_5:
    config:
      param_epoch: 4
  get_epoch_6:
    config:
      param_epoch: 5
  get_epoch_7:
    config:
      param_epoch: 6
  get_epoch_8:
    config:
      param_epoch: 7
  get_epoch_9:
    config:
      param_epoch: 8

